// src/views/Home.vue
<template>
  <div class="home">
    <a :href="SERVER_ADDRESS" target="_blank"><img alt="NetsBlox logo" src="/images/logo.png"></a>
    <p>Welcome to NetsBlox teacher dashboard.</p>
    <p>Server address: <a :href="SERVER_ADDRESS" target="_blank">{{ SERVER_ADDRESS }}</a></p>
  </div>
</template>

<script>
import store from '@/store';

export default {
  name: 'home',
  components: {
  },
  data() {
    return {
      SERVER_ADDRESS: store.state.SERVER_ADDRESS,
    }
  }
}
</script>

<style scoped>
img {
  max-width: 10vw;
  max-height: 10vh;
}
</style>

// src/routes/Home.svelte
<script lang="ts">
    export let server;
</script>

<img src="images/logo.png" id="nb-logo" alt="NetsBlox Logo" />

<h2>Welcome to the NetsBlox teacher dashboard!</h2>

<p>
    Server address: <a href={server} target="blank">{server}</a>
</p>

<style>
    #nb-logo {
        width: 192px;
    }
</style>
