// src/routes/Help.svelte
<script lang="ts">
</script>

<h2>Help and FAQ</h2>
Here you can find help for different sections of the dashboard. If there is something missing here that you think should be here please let us know. You can also read more on NetsBlox and Roboscape on<a
    href="http://netsblox.org"
    target="_blank">NetsBlox's help page</a
>

<section class="content">
    <h3>RoboScape</h3>
    <p>This section allows you to see the robots you have registered as your own, change their access level and control which users can access them.</p>
    <p>
        Once you successfully finish the ownership process for a robot you'll see it pop up under "Your Robots" section. From there clicking on each robot brings you to a page where you can add, view
        and manage the users access to that robot.
    </p>
    <h5>Adding & Managing Users</h5>
    <p>
        Click the plus icon next to "Users", type in a username and click the check mark to finalize adding the user. You can add multiple users at the same time by providing multiple usernames
        separated by a comma and a space. For example: "user1, user2"
    </p>
    <p>To enable or disable a user's access to the robot just click the checkmark under hasAccess column for those users.</p>
    <h5>Changing Robot's Mode</h5>
    <p>The robots can operate in two mode: "Protected" and "Public":</p>
    <ul>
        <li>Public mode: any user can interact with the robot</li>
        <li>Protected mode: only authorized users can interact with the robot</li>
    </ul>

    <h3>Groups</h3>
    <p>Documentation for this section will be added a future version.</p>
</section>

<style>
    section.content {
        text-align: left;
    }
</style>

// src/views/Help.vue
<template>
  <main>
    <h2>Help and FAQ</h2>
    Here you can find help for different sections of the dashboard.
    If there is something missing here that you think should be here please let us know.
    You can also read more on NetsBlox and Roboscape on <a href="http://netsblox.org" target="_blank">NetsBlox's help page</a>

    <section class="content">
      <h3>RoboScape</h3>
      <p>
      This section allows you to see the robots you have registered as your own, change their access level and control which users can access them.
      </p>
      <p>
      Once you successfully finish the ownership process for a robot you'll see it pop up under "Your Robots" section.
      From there clicking on each robot brings you to a page where you can add, view and manage the users access to that robot.
      </p>
      <h5>Adding & Managing Users</h5>
      <p>
      Click the plus icon next to "Users", type in a username and click the check mark to finalize adding the user.
      You can add multiple users at the same time by providing multiple usernames separated by a comma and a space. For example: "user1, user2"
      </p>
      <p>
      To enable or disable a user's access to the robot just click the checkmark under hasAccess column for those users.
      </p>
      <h5>Changing Robot's Mode</h5>
      <p>
      The robots can operate in two mode: "Protected" and "Public":
      <ul>
        <li>Public mode: any user can interact with the robot</li>
        <li>Protected mode: only authorized users can interact with the robot</li>
      </ul>
      </p>

      <h3>Groups</h3>
      <p>
      Documentation for this section will be added a future version.
      </p>

    </section>

  </main>
</template>

<style scoped>
section.content {
  text-align: left;
}
</style>
